package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.haolei.entity.Person;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    ");
Person person = (Person)session.getAttribute("logined"); 
      out.write("\r\n");
      out.write("    <title>CMS--");
      out.print(person.getUsername());
      out.write(" onLine</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0\r\n");
      out.write("\t}\r\n");
      out.write("\t.style1 {\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.style2 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-family: 华文琥珀;\r\n");
      out.write("\t\tfont-size:59px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.style3 {\t\t\t}\r\n");
      out.write("\t.style4 {\t\t\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tborder:1px;\r\n");
      out.write("\t\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 1px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.style6 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.style7 {\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t\tfont-size: smaller;\r\n");
      out.write("\t\tcolor: #CC6600;\r\n");
      out.write("\t}\r\n");
      out.write("\t.style8 {\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 1px;\r\n");
      out.write("\t\tfont-family: \"Courier New\", Courier, monospace;\r\n");
      out.write("\t\tfont-size: small;\r\n");
      out.write("\t\tcolor: #CC6600;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.style9 {\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.style10 {\r\n");
      out.write("\t\tborder: 0px solid #003300;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.style11 {\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t.style12 {\r\n");
      out.write("\t  float:left\r\n");
      out.write("\t}\r\n");
      out.write("\t.style13 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: smaller;\r\n");
      out.write("\t\tcolor: #CC6600;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.wupin_table {\r\n");
      out.write("\tborder: 1px solid #666699;\r\n");
      out.write("\t}\r\n");
      out.write("\t.wupin_table_tr_td {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.one{\r\n");
      out.write("\t\tborder: 1px solid #9999FF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.two {\r\n");
      out.write("\t\tborder: 1px solid #CCCCFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.three {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.four {\r\n");
      out.write("\t\tborder: 0px solid #FF9933;\r\n");
      out.write("\t}\r\n");
      out.write("\t.five {\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 1px;\r\n");
      out.write("\t\tborder: 1px solid teal;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t<!--wupin_jjzt_jjzt_table_style-->\r\n");
      out.write("\t.jjstatus_table {\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.jjstatus_table_th {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 1px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.jjstatus_table_tr_td {\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 1px;\r\n");
      out.write("\t}\r\n");
      out.write("\t<!--wupin_jjzt_jjzt_table_style------------------------------>\r\n");
      out.write("\t\r\n");
      out.write("\t.wupin_jjzt_table {\r\n");
      out.write("\t\tborder: 1px solid #6699FF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.wupin_jjzt_table_tr_td {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tbackground-color: #6699FF;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.10.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction load(){\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#goods\").hide();\r\n");
      out.write("\t\t\t$(\"#maintain\").hide();\r\n");
      out.write("\t\t\t$(\"#resignation\").hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#of\").hide();\r\n");
      out.write("\t\t\t$(\"#bo\").hide();\r\n");
      out.write("\t\t\t$(\"#zt\").show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#jjstatus\").show();\r\n");
      out.write("\t\t\t$(\"#jjhistory\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction c1(){\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\"#cmail\").show();\r\n");
      out.write("\t\t\t\t$(\"#goods\").hide();\r\n");
      out.write("\t\t\t\t$(\"#maintain\").hide();\r\n");
      out.write("\t\t\t\t$(\"#resignation\").hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction c2(){\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\"#goods\").show();\r\n");
      out.write("\t\t\t\t$(\"#cmail\").hide();\r\n");
      out.write("\t\t\t\t$(\"#maintain\").hide();\r\n");
      out.write("\t\t\t\t$(\"#resignation\").hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction c3(){\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\"#maintain\").show();\r\n");
      out.write("\t\t\t\t$(\"#cmail\").hide();\r\n");
      out.write("\t\t\t\t$(\"#goods\").hide();\r\n");
      out.write("\t\t\t\t$(\"#resignation\").hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction c4(){\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\"#resignation\").show();\r\n");
      out.write("\t\t\t\t$(\"#cmail\").hide();\r\n");
      out.write("\t\t\t\t$(\"#goods\").hide();\r\n");
      out.write("\t\t\t\t$(\"#maintain\").hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction b1(){\r\n");
      out.write("\t\t\t$(\"#bo\").show();\r\n");
      out.write("\t\t\t$(\"#of\").hide();\r\n");
      out.write("\t\t\t$(\"#zt\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction o1(){\r\n");
      out.write("\t\t\t$(\"#of\").show();\r\n");
      out.write("\t\t\t$(\"#bo\").hide();\r\n");
      out.write("\t\t\t$(\"#zt\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction jj(){\r\n");
      out.write("\t\t\t$(\"#bo\").hide();\r\n");
      out.write("\t\t\t$(\"#of\").hide();\r\n");
      out.write("\t\t\t$(\"#zt\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction jjstatus_show(){ \r\n");
      out.write("\t\t\t$(\"#jjstatus\").show();\r\n");
      out.write("\t\t\t$(\"#jjhistory\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jjstatushistory_show(){\r\n");
      out.write("\t\t\t$(\"#jjstatus\").hide();\r\n");
      out.write("\t\t\t$(\"#jjhistory\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write(" <body onload=\"load()\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"border-color: inherit; border-width: 0px; width:100%; height:100%; \" class=\"style9\">\r\n");
      out.write("\t<table border=\"0\" cellspacing=\"0\" class=\"style1\" style=\"width: 100%; height: 884px\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"height: 60px\">\r\n");
      out.write("\t\t\t<table cellspacing=\"0\" class=\"style1\" style=\"width: 100%;background-color:silver; height: 100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"style2\" style=\"width: 167px\"  bgcolor=\"#C0C0C0\">\r\n");
      out.write("\t\t\t\t\t<strong>C M S</strong></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"style3\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"1\" class=\"style4\" style=\"width: 400px; height: 60px\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"style13\">IP:");
      out.print((session.getAttribute("ip").toString()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"style7\">修改个人信息</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"style13\">2013/07/11 12:45</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"style7\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"style13\">");
      out.print(person.getUsername() );
      out.write(" 欢迎登录CMS</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"style7\">log out</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"2\" style=\"width: 160px\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t<table cellspacing=\"1\" class=\"style8\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\" style=\"height: 148px\" valign=\"middle\">\r\n");
      out.write("\t\t\t\t\t<img src=\"image/userimage.jpg\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"1\" class=\"style8\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 35px\">帮派：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 35px\">测试部</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 36px\">书信：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 36px\">15815523495</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 31px\">职务：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 31px\">配置管理员</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 35px\">装备：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 35px\">自家法宝</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<table cellpadding=\"2\" class=\"style10\" style=\"width: 100%; height: 158%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 26px\"  class=\"style11\" >lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 26px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 27px\"  class=\"style11\">lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 27px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"   class=\"style11\">lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 28px\"  class=\"style11\">lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 28px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">lenovo y450</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"height: 24px\"  class=\"style11\">x1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"height: 41px\">\r\n");
      out.write("\t\t\t<table cellspacing=\"4\" class=\"style12\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#666699\" class=\"style6\" onclick=\"c1()\"><strong>公 司 邮 箱</strong></td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#666699\" class=\"style6\" onclick=\"c2()\"><strong>物 品 借 记</strong></td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#666699\" class=\"style6\" onclick=\"c3()\"><strong>硬件登记/维护</strong></td>\r\n");
      out.write("\t\t\t\t\t<td bgcolor=\"#666699\" class=\"style6\" onclick=\"c4()\"><strong>离 职 流 程</strong></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"height: 718px; padding-left:5px\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t<!--cmail-->\r\n");
      out.write("\t\t\t<div id=\"cmail\" style=\"position: absolute; width: 1065px; height: 718px; z-index: 1\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<head>\r\n");
      out.write("\t\t\t\t\t<meta content=\"zh-cn\" http-equiv=\"Content-Language\" />\r\n");
      out.write("\t\t\t\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t.tab1_1{\r\n");
      out.write("\t\t\t\t\t\tbackground-color:silver\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.tab1 {\r\n");
      out.write("\t\t\t\t\t\tborder: 0px solid #3366FF;\r\n");
      out.write("\t\t\t\t\t\tbackground-color: #9999FF;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.head1{\r\n");
      out.write("\t\t\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t\t\tfont-size: x-large;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</style>\r\n");
      out.write("\t\t\t\t\t</head>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<body>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"1\" class=\"tab1\" style=\"width: 1000px; height: 700px\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"head1\" colspan=\"3\" style=\"height: 38px;text-align: center;font-size: x-large\"><strong>邮 箱 管 理</strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 246px; width: 500px\" align=\"left\" bgcolor=\"#C0C0C0\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" height=\"17\" src=\"image/attention.png\" width=\"17\" /> 未申请公司邮箱<br />\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 请在如下表格中填入您的gmail邮箱地址和您的手机号。<br />\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 246px; width: 15px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height: 246px\" align=\"left\" bgcolor=\"#C0C0C0\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" height=\"17\" src=\"image/attention.png\" width=\"17\" />已经开通公司邮箱<br />\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; 如果您需要改换另外一个gmail邮箱地址，请在下面表格中填入新的gmail。按修改按钮提交。</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\" style=\"width: 500px\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table cellspacing=\"1\" class=\"tab1_1\" style=\"width: 100%; height: 100%\" style=\"float:left;background-color:silver\r\n");
      out.write("\t\t\t\t\t\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>gmail:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Text1\" style=\"width: 197px; height: 32px\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>手机号：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Text2\" style=\"width: 197px; height: 32px\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp; </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"Button1\" type=\"button\" value=\"申  请\" style=\"width: 91px; height: 53px\" /></form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 15px\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<table cellspacing=\"1\" class=\"tab1_1\" style=\"width: 100%; height: 100%\" style=\"float:left;background-color:silver\r\n");
      out.write("\t\t\t\t\t\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>gmail:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Text1\" style=\"width: 197px; height: 32px\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>公司邮箱：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Text2\" style=\"width: 197px; height: 32px\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>状态：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>已开通</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"Button1\" type=\"button\" value=\"修  改\" style=\"width: 91px; height: 53px\" /></form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</body>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</html>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--cmail------------------------------------------------------------------------------------->\r\n");
      out.write("\t\t\t<!--goods-->\r\n");
      out.write("\t\t\t<div id=\"goods\" style=\"position: absolute; width: 1065px; height: 718px; z-index: 2\">\r\n");
      out.write("\t\t\t<table cellspacing=\"1\" class=\"wupin_table\" style=\"width: 1000px; height: 700px\">\r\n");
      out.write("\t<tr bgcolor=\"#CCCCFF\">\r\n");
      out.write("\t\t<td class=\"wupin_table_tr_td\" style=\"height: 26px; width: 304px\" onclick=\"jj()\"><strong>\r\n");
      out.write("\t\t我的借记状态</strong></td>\r\n");
      out.write("\t\t<td class=\"wupin_table_tr_td\" style=\"height: 26px; width: 332px\" onclick=\"b1()\">\r\n");
      out.write("\t\t<strong>图书借记</strong></td>\r\n");
      out.write("\t\t<td class=\"wupin_table_tr_td\" style=\"height: 26px\" onclick=\"o1()\"><strong>办公用品借记</strong></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"left\" colspan=\"3\" valign=\"top\">\r\n");
      out.write("\t\t\t<div id=\"bo\" style=\"position: absolute; width: 999px; height: 673px; z-index: 1\">\r\n");
      out.write("\t\t\t<!--图书页-->\r\n");
      out.write("\t\t\t<table cellspacing=\"1\" class=\"one\" style=\"width: 996px; height: 500px\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"height: 12px; width: 991px;\">图书查询：</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"left\" style=\"height: 54px; width: 991px;\" valign=\"top\">\r\n");
      out.write("\t\t<table cellspacing=\"1\" class=\"two\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>分类：</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t\t\t<form method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input name=\"Text1\" style=\"width: 84px\" type=\"text\" /></form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>出版社：</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"Text2\" style=\"width: 91px\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t<td>作者：</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"Text3\" style=\"width: 103px\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t<td>书名：</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"Text4\" type=\"text\" /></td>\r\n");
      out.write("\t\t\t\t<td class=\"three\">\r\n");
      out.write("\t\t\t\t\t<input name=\"Button1\" type=\"button\" value=\"查 找\" style=\"width: 42px\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"height: 19px; width: 991px;\">查询结果：</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"left\" valign=\"top\" style=\"width: 991px\">\r\n");
      out.write("\t\t<table cellspacing=\"1\" style=\"width: 100%; height: 100%;border: 0px solid #CCCCFF;\r\n");
      out.write("\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height: 526px\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table cellspacing=\"0\" class=\"four\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"five\">分类</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"five\">作者</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"five\">出版社</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"five\">书名</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"five\">状态</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"five\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>分页按钮区</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"of\" style=\"position: absolute; width: 999px; height: 673px; z-index: 2\">\r\n");
      out.write("\t\t\t在村民解建勇家，习近平同一家三代围坐一起，详细询问家庭收入怎么样、孩子书读得怎么样、村里的公共服务好不好？他说，让农民群众不断过上好日子，是体现我们党的宗旨的一个重要方面，我们还要继续努力。在村里的综合超市，习近平看货架商品，问蔬菜价格，同前来购物的群众亲切交流。他指出，超市连接百姓生活，是农村服务业的一个发展趋势，要加强农村流通网络建设，为群众生活提供方便、快捷的服务\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"zt\" style=\"position: absolute; width: 999px; height: 673px; z-index: 3\">\r\n");
      out.write("\t\t\t<table cellspacing=\"1\" class=\"wupin_jjzt_table\" style=\"width: 965px; height: 654px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"height: 43px\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"0\" cellspacing=\"2\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 465px; background-color: #6699FF;\" class=\"wupin_jjzt_table_tr_td\" onclick=\"jjstatus_show()\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>我 的 借 记 状 态</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"wupin_jjzt_table_tr_td\" onclick=\"jjstatushistory_show()\"><strong>历 史 记 录 </strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" style=\"height: 558px\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<!--借记状态DIV-->\r\n");
      out.write("\t\t\t\t\t<div id=\"jjstatus\" style=\"position: absolute; width: 960px; height: 558px; z-index: 1\">\r\n");
      out.write("\t\t\t\t\t\t<!--table-->\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" class=\"jjstatus_table\" style=\"width: 960px; height: 558px\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">类型</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">名称</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">条码</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">借出时间 </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">归还时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">剩余时限</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--借记状态DIV---------------------------------------------------------------->\r\n");
      out.write("\t\t\t\t\t<!--借记历史DIV-->\r\n");
      out.write("\t\t\t\t\t<div id=\"jjhistory\" style=\"position: absolute; width: 960px; height: 558px; z-index: 2\">\r\n");
      out.write("\t\t\t\t\t\t<!--table-->\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" class=\"jjstatus_table\" style=\"width: 960px; height: 558px\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">类型</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">名称</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">条码</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">借出时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">借用时限</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">实际归还时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_th\">状态</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"jjstatus_table_tr_td\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--借记历史DIV----------------------------------------------------------------->\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>分页按钮栏</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--goods------------------------------------------------------------------------------------->\r\n");
      out.write("\t\t\t<!--maintain-->\r\n");
      out.write("\t\t\t<div id=\"maintain\" style=\"position: absolute; width: 1065px; height: 718px; z-index:3\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t机械公司内部控制状况及建议\r\n");
      out.write("\t\t\t\t\t一、内部控制的含义 内部会计控制,是单位为了提高会计信息质量,保护资产的安全、完整,确保有关法律法规和规章制度的贯彻执行等而制定和实施的一系列控制方法、措施和程序。保证会计信息的真实性是内部控制发展的主线...\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--maintain---------------------------------------------------------------------------------->\r\n");
      out.write("\t\t\t<!--resignation-->\r\n");
      out.write("\t\t\t<div id=\"resignation\" style=\"position: absolute; width: 1065px; height: 718px; z-index: 4\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t分析农村公共服务需求及地方管理创新\r\n");
      out.write("\t\t\t\t\t农民对公共服务需求主要受以下因素影响 1收入对公共产品和服务需求的影响。收入水平高低影响了对公共产品和服务需求的数量与结构。收入能改变约束条件;随着个人收入的增长,政府的公共支出规模会增加(瓦格纳法则);收...\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--resignation------------------------------------------------------------------------------->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"#C0C0C0\" class=\"style6\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t<span style=\"color: rgb(81, 81, 81); font-family: Arial; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 24px; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; display: inline !important; float: none;\">\r\n");
      out.write("\t\tCopyright ©&nbsp; 2013 zyeeda. All Rights Reserved</span>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
